# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/EECE4632/HW4/Vivado/divide_by_13/stream.srcs/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_divide_by_13_0_0/dma_axis_ip_example_divide_by_13_0_0.xci
# IP: The module: 'dma_axis_ip_example_divide_by_13_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/EECE4632/HW4/Vivado/divide_by_13/stream.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_divide_by_13_0_0/constraints/divide_by_13_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_divide_by_13_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/EECE4632/HW4/Vivado/divide_by_13/stream.srcs/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_divide_by_13_0_0/dma_axis_ip_example_divide_by_13_0_0.xci
# IP: The module: 'dma_axis_ip_example_divide_by_13_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/EECE4632/HW4/Vivado/divide_by_13/stream.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_divide_by_13_0_0/constraints/divide_by_13_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_divide_by_13_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
