// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mmult_hw_mmult_hw_Pipeline_VITIS_LOOP_36_3_VITIS_LOOP_37_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        sext_ln36,
        B_address0,
        B_ce0,
        B_we0,
        B_d0,
        B_1_address0,
        B_1_ce0,
        B_1_we0,
        B_1_d0,
        B_2_address0,
        B_2_ce0,
        B_2_we0,
        B_2_d0,
        B_3_address0,
        B_3_ce0,
        B_3_we0,
        B_3_d0,
        B_4_address0,
        B_4_ce0,
        B_4_we0,
        B_4_d0,
        B_5_address0,
        B_5_ce0,
        B_5_we0,
        B_5_d0,
        B_6_address0,
        B_6_ce0,
        B_6_we0,
        B_6_d0,
        B_7_address0,
        B_7_ce0,
        B_7_we0,
        B_7_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [31:0] m_axi_gmem_WDATA;
output  [3:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [31:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [61:0] sext_ln36;
output  [10:0] B_address0;
output   B_ce0;
output   B_we0;
output  [31:0] B_d0;
output  [10:0] B_1_address0;
output   B_1_ce0;
output   B_1_we0;
output  [31:0] B_1_d0;
output  [10:0] B_2_address0;
output   B_2_ce0;
output   B_2_we0;
output  [31:0] B_2_d0;
output  [10:0] B_3_address0;
output   B_3_ce0;
output   B_3_we0;
output  [31:0] B_3_d0;
output  [10:0] B_4_address0;
output   B_4_ce0;
output   B_4_we0;
output  [31:0] B_4_d0;
output  [10:0] B_5_address0;
output   B_5_ce0;
output   B_5_we0;
output  [31:0] B_5_d0;
output  [10:0] B_6_address0;
output   B_6_ce0;
output   B_6_we0;
output  [31:0] B_6_d0;
output  [10:0] B_7_address0;
output   B_7_ce0;
output   B_7_we0;
output  [31:0] B_7_d0;

reg ap_idle;
reg m_axi_gmem_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln36_fu_243_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] gmem_addr_read_reg_390;
wire   [63:0] zext_ln39_1_fu_332_p1;
reg   [7:0] j_fu_94;
wire   [7:0] add_ln37_fu_344_p2;
wire    ap_loop_init;
reg   [7:0] i_fu_98;
wire   [7:0] select_ln36_1_fu_292_p3;
reg   [14:0] indvar_flatten262_fu_102;
wire   [14:0] add_ln36_1_fu_249_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten262_load;
reg    B_6_we0_local;
wire   [2:0] trunc_ln36_fu_300_p1;
reg    B_6_ce0_local;
reg    B_5_we0_local;
reg    B_5_ce0_local;
reg    B_4_we0_local;
reg    B_4_ce0_local;
reg    B_3_we0_local;
reg    B_3_ce0_local;
reg    B_2_we0_local;
reg    B_2_ce0_local;
reg    B_1_we0_local;
reg    B_1_ce0_local;
reg    B_we0_local;
reg    B_ce0_local;
reg    B_7_we0_local;
reg    B_7_ce0_local;
wire   [0:0] icmp_ln37_fu_278_p2;
wire   [7:0] add_ln36_fu_272_p2;
wire   [3:0] lshr_ln1_fu_304_p4;
wire   [7:0] select_ln36_fu_284_p3;
wire   [10:0] tmp_1_fu_314_p3;
wire   [10:0] zext_ln39_fu_322_p1;
wire   [10:0] add_ln39_fu_326_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_94 = 8'd0;
#0 i_fu_98 = 8'd0;
#0 indvar_flatten262_fu_102 = 15'd0;
#0 ap_done_reg = 1'b0;
end

mmult_hw_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            i_fu_98 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            i_fu_98 <= select_ln36_1_fu_292_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln36_fu_243_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten262_fu_102 <= add_ln36_1_fu_249_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten262_fu_102 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            j_fu_94 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            j_fu_94 <= add_ln37_fu_344_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        gmem_addr_read_reg_390 <= m_axi_gmem_RDATA;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_1_ce0_local = 1'b1;
    end else begin
        B_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln36_fu_300_p1 == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_1_we0_local = 1'b1;
    end else begin
        B_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_2_ce0_local = 1'b1;
    end else begin
        B_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln36_fu_300_p1 == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_2_we0_local = 1'b1;
    end else begin
        B_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_3_ce0_local = 1'b1;
    end else begin
        B_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln36_fu_300_p1 == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_3_we0_local = 1'b1;
    end else begin
        B_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_4_ce0_local = 1'b1;
    end else begin
        B_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln36_fu_300_p1 == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_4_we0_local = 1'b1;
    end else begin
        B_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_5_ce0_local = 1'b1;
    end else begin
        B_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln36_fu_300_p1 == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_5_we0_local = 1'b1;
    end else begin
        B_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_6_ce0_local = 1'b1;
    end else begin
        B_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln36_fu_300_p1 == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_6_we0_local = 1'b1;
    end else begin
        B_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_7_ce0_local = 1'b1;
    end else begin
        B_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln36_fu_300_p1 == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_7_we0_local = 1'b1;
    end else begin
        B_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_ce0_local = 1'b1;
    end else begin
        B_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln36_fu_300_p1 == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_we0_local = 1'b1;
    end else begin
        B_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_243_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten262_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten262_load = indvar_flatten262_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_1_address0 = zext_ln39_1_fu_332_p1;

assign B_1_ce0 = B_1_ce0_local;

assign B_1_d0 = gmem_addr_read_reg_390;

assign B_1_we0 = B_1_we0_local;

assign B_2_address0 = zext_ln39_1_fu_332_p1;

assign B_2_ce0 = B_2_ce0_local;

assign B_2_d0 = gmem_addr_read_reg_390;

assign B_2_we0 = B_2_we0_local;

assign B_3_address0 = zext_ln39_1_fu_332_p1;

assign B_3_ce0 = B_3_ce0_local;

assign B_3_d0 = gmem_addr_read_reg_390;

assign B_3_we0 = B_3_we0_local;

assign B_4_address0 = zext_ln39_1_fu_332_p1;

assign B_4_ce0 = B_4_ce0_local;

assign B_4_d0 = gmem_addr_read_reg_390;

assign B_4_we0 = B_4_we0_local;

assign B_5_address0 = zext_ln39_1_fu_332_p1;

assign B_5_ce0 = B_5_ce0_local;

assign B_5_d0 = gmem_addr_read_reg_390;

assign B_5_we0 = B_5_we0_local;

assign B_6_address0 = zext_ln39_1_fu_332_p1;

assign B_6_ce0 = B_6_ce0_local;

assign B_6_d0 = gmem_addr_read_reg_390;

assign B_6_we0 = B_6_we0_local;

assign B_7_address0 = zext_ln39_1_fu_332_p1;

assign B_7_ce0 = B_7_ce0_local;

assign B_7_d0 = gmem_addr_read_reg_390;

assign B_7_we0 = B_7_we0_local;

assign B_address0 = zext_ln39_1_fu_332_p1;

assign B_ce0 = B_ce0_local;

assign B_d0 = gmem_addr_read_reg_390;

assign B_we0 = B_we0_local;

assign add_ln36_1_fu_249_p2 = (ap_sig_allocacmp_indvar_flatten262_load + 15'd1);

assign add_ln36_fu_272_p2 = (i_fu_98 + 8'd1);

assign add_ln37_fu_344_p2 = (select_ln36_fu_284_p3 + 8'd1);

assign add_ln39_fu_326_p2 = (tmp_1_fu_314_p3 + zext_ln39_fu_322_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (m_axi_gmem_RVALID == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln36_fu_243_p2 = ((ap_sig_allocacmp_indvar_flatten262_load == 15'd16384) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_278_p2 = ((j_fu_94 == 8'd128) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_304_p4 = {{select_ln36_1_fu_292_p3[6:3]}};

assign m_axi_gmem_ARADDR = 64'd0;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd0;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_ARVALID = 1'b0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 32'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 4'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign select_ln36_1_fu_292_p3 = ((icmp_ln37_fu_278_p2[0:0] == 1'b1) ? add_ln36_fu_272_p2 : i_fu_98);

assign select_ln36_fu_284_p3 = ((icmp_ln37_fu_278_p2[0:0] == 1'b1) ? 8'd0 : j_fu_94);

assign tmp_1_fu_314_p3 = {{lshr_ln1_fu_304_p4}, {7'd0}};

assign trunc_ln36_fu_300_p1 = select_ln36_1_fu_292_p3[2:0];

assign zext_ln39_1_fu_332_p1 = add_ln39_fu_326_p2;

assign zext_ln39_fu_322_p1 = select_ln36_fu_284_p3;

endmodule //mmult_hw_mmult_hw_Pipeline_VITIS_LOOP_36_3_VITIS_LOOP_37_4
