# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/divisible/divisible.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divisible || ORIG_REF_NAME==divisible} -quiet] -quiet

# IP: bd/divisible/ip/divisible_proc_sys_reset_0_0/divisible_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divisible_proc_sys_reset_0_0 || ORIG_REF_NAME==divisible_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/divisible/ip/divisible_zynq_ultra_ps_e_0_0/divisible_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divisible_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==divisible_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/divisible/ip/divisible_ps8_0_axi_periph_0/divisible_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divisible_ps8_0_axi_periph_0 || ORIG_REF_NAME==divisible_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/divisible/ip/divisible_divisible_0_1/divisible_divisible_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divisible_divisible_0_1 || ORIG_REF_NAME==divisible_divisible_0_1} -quiet] -quiet

# IP: bd/divisible/ip/divisible_auto_pc_0/divisible_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divisible_auto_pc_0 || ORIG_REF_NAME==divisible_auto_pc_0} -quiet] -quiet

# XDC: f:/HW3/Vivado/divisible/divisible.gen/sources_1/bd/divisible/divisible_ooc.xdc
