# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/HW3/Vivado/divisible/divisible.srcs/sources_1/bd/divisible/ip/divisible_divisible_0_1/divisible_divisible_0_1.xci
# IP: The module: 'divisible_divisible_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/HW3/Vivado/divisible/divisible.gen/sources_1/bd/divisible/ip/divisible_divisible_0_1/constraints/divisible_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divisible_divisible_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/HW3/Vivado/divisible/divisible.srcs/sources_1/bd/divisible/ip/divisible_divisible_0_1/divisible_divisible_0_1.xci
# IP: The module: 'divisible_divisible_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/HW3/Vivado/divisible/divisible.gen/sources_1/bd/divisible/ip/divisible_divisible_0_1/constraints/divisible_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divisible_divisible_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
