# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/adder/adder.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder} -quiet] -quiet

# IP: bd/adder/ip/adder_proc_sys_reset_0_0/adder_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_proc_sys_reset_0_0 || ORIG_REF_NAME==adder_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/adder/ip/adder_zynq_ultra_ps_e_0_0/adder_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==adder_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/adder/ip/adder_add_0_0/adder_add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_add_0_0 || ORIG_REF_NAME==adder_add_0_0} -quiet] -quiet

# IP: bd/adder/ip/adder_auto_pc_0/adder_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_auto_pc_0 || ORIG_REF_NAME==adder_auto_pc_0} -quiet] -quiet

# IP: bd/adder/ip/adder_ps8_0_axi_periph_0/adder_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_ps8_0_axi_periph_0 || ORIG_REF_NAME==adder_ps8_0_axi_periph_0} -quiet] -quiet

# XDC: c:/Users/langweil.m/Documents/Lab2_vivado/Lab2/Lab2.gen/sources_1/bd/adder/adder_ooc.xdc
