# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/EECE4632/Lab3/Vivado/stream/stream.srcs/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_us_0/dma_axis_ip_example_auto_us_0.xci
# IP: The module: 'dma_axis_ip_example_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/EECE4632/Lab3/Vivado/stream/stream.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_us_0/dma_axis_ip_example_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_auto_us_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/EECE4632/Lab3/Vivado/stream/stream.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_us_0/dma_axis_ip_example_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/EECE4632/Lab3/Vivado/stream/stream.srcs/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_us_0/dma_axis_ip_example_auto_us_0.xci
# IP: The module: 'dma_axis_ip_example_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/EECE4632/Lab3/Vivado/stream/stream.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_us_0/dma_axis_ip_example_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/EECE4632/Lab3/Vivado/stream/stream.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_us_0/dma_axis_ip_example_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
